### ISSUE TITLE
When will there be some content ;-)

### ISSUE THREAD

**Issue by timmli** [xmg-hhu/webgui#1]

**Comment by SamihYounes** [comment]
On 07/03/2015 11:28 AM, Timm Lichte wrote:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/xmg-hhu/webgui/issues/1>.
>
Hi Timm

I have finished a prototype of the file uploader. I shall connect it to 
the application very soon :)

http://xmg.phil.hhu.de/upload_files/

Best
Younes

**Comment by timmli** [comment]
Wonderful!
